-- AlterTable
ALTER TABLE `user` ADD COLUMN `about` VARCHAR(191) NULL,
    ADD COLUMN `agencyName` VARCHAR(191) NULL,
    ADD COLUMN `location` VARCHAR(191) NULL,
    ADD COLUMN `phone` VARCHAR(191) NULL,
    ADD COLUMN `website` VARCHAR(191) NULL;
